# -*- coding: utf-8 -*-
"""Question catalogue — wording taken from the CIS 2026 questionnaire."""

from __future__ import annotations

# Sections follow the questionnaire structure (closed questions only).
QUESTIONS: list[dict] = [
    # --- Part I: General impressions ---
    {
        "id": "q2",
        "section": "General impressions",
        "label": "Q2. Interest in China",
        "text": "How interested are you in China?",
        "kind": "single",
        "col": "q2",
        "order": [
            "Extremely interested",
            "Very interested",
            "Somewhat interested",
            "Slightly interested",
            "Not interested at all",
        ],
        "positive": ["Extremely interested", "Very interested"],
    },
    {
        "id": "q3",
        "section": "General impressions",
        "label": "Q3. Attitude toward China",
        "text": "From a subjective perspective, what is your attitude toward China?",
        "kind": "single",
        "col": "q3",
        "order": [
            "Strongly favorable",
            "Favorable",
            "Slightly favorable",
            "Neither favorable nor unfavorable",
            "Slightly unfavorable",
            "Unfavorable",
            "Strongly unfavorable",
        ],
        "positive": ["Strongly favorable", "Favorable", "Slightly favorable"],
    },
    {
        "id": "q4",
        "section": "General impressions",
        "label": "Q4. Knowledge of China",
        "text": "From an objective perspective, how much do you know about China?",
        "kind": "single",
        "col": "q4",
        "order": ["Very well", "Much", "Some", "A little"],
        "positive": ["Very well", "Much"],
    },
    {
        "id": "q5",
        "section": "General impressions",
        "label": "Q5. China–your country relationship",
        "text": "China is a/an … of/for your country, in consideration of the relationship between your country and China.",
        "kind": "single",
        "col": "q5",
        "order": [
            "Friendly country",
            "Strategic cooperative partner",
            "Country with normal relations",
            "Competitor",
            "Enemy",
            "Other",
        ],
        "positive": ["Friendly country", "Strategic cooperative partner"],
    },
    {
        "id": "q6",
        "section": "General impressions",
        "label": "Q6. Desired future relationship",
        "text": "What change would you like to see for the relationship between your country and China in the future?",
        "kind": "single",
        "col": "q6",
        "order": [
            "Much closer and much more friendly",
            "Closer and more friendly",
            "Status quo",
            "More distant",
            "More hostile",
            "Other",
        ],
        "positive": ["Much closer and much more friendly", "Closer and more friendly"],
    },
    {
        "id": "q7",
        "section": "General impressions",
        "label": "Q7. Visit to Chinese mainland",
        "text": "Have you visited the Chinese mainland in the past year?",
        "kind": "single",
        "col": "q7",
        "order": None,
        "positive": None,
    },
    # --- Impressions battery ---
    {
        "id": "q11a",
        "section": "Impressions of China",
        "label": "Q11(1). Overall impression of China",
        "text": "What is your impression of China? — Overall impression of China",
        "kind": "single",
        "col": "q11a",
        "order": [
            "Very good",
            "Good",
            "Neutral (Slightly good)",
            "Neutral (Slightly bad)",
            "Bad",
            "Very bad",
            "Don't know/Hard to answer",
        ],
        "positive": ["Very good", "Good", "Neutral (Slightly good)"],
    },
    {
        "id": "q11b",
        "section": "Impressions of China",
        "label": "Q11(2). China’s economic development",
        "text": "What is your impression of China? — Impression of China’s economic development",
        "kind": "single",
        "col": "q11b",
        "order": [
            "Very good",
            "Good",
            "Neutral (Slightly good)",
            "Neutral (Slightly bad)",
            "Bad",
            "Very bad",
            "Don't know/Hard to answer",
        ],
        "positive": ["Very good", "Good", "Neutral (Slightly good)"],
    },
    {
        "id": "q11c",
        "section": "Impressions of China",
        "label": "Q11(3). China’s science and technology",
        "text": "What is your impression of China? — Impression of China’s science and technology",
        "kind": "single",
        "col": "q11c",
        "order": [
            "Very good",
            "Good",
            "Neutral (Slightly good)",
            "Neutral (Slightly bad)",
            "Bad",
            "Very bad",
            "Don't know/Hard to answer",
        ],
        "positive": ["Very good", "Good", "Neutral (Slightly good)"],
    },
    {
        "id": "q11e",
        "section": "Impressions of China",
        "label": "Q11(5). Chinese culture",
        "text": "What is your impression of China? — Impression of Chinese culture",
        "kind": "single",
        "col": "q11e",
        "order": [
            "Very good",
            "Good",
            "Neutral (Slightly good)",
            "Neutral (Slightly bad)",
            "Bad",
            "Very bad",
            "Don't know/Hard to answer",
        ],
        "positive": ["Very good", "Good", "Neutral (Slightly good)"],
    },
    {
        "id": "q11f",
        "section": "Impressions of China",
        "label": "Q11(6). Chinese government",
        "text": "What is your impression of China? — Impression of the Chinese government",
        "kind": "single",
        "col": "q11f",
        "order": [
            "Very good",
            "Good",
            "Neutral (Slightly good)",
            "Neutral (Slightly bad)",
            "Bad",
            "Very bad",
            "Don't know/Hard to answer",
        ],
        "positive": ["Very good", "Good", "Neutral (Slightly good)"],
    },
    {
        "id": "q12a",
        "section": "Impressions of Chinese people",
        "label": "Q12(1). Overall impression of Chinese people",
        "text": "What is your impression of the Chinese people? — Overall impression",
        "kind": "single",
        "col": "q12a",
        "order": [
            "Very good",
            "Good",
            "Neutral (Slightly good)",
            "Neutral (Slightly bad)",
            "Bad",
            "Very bad",
            "Don't know/Hard to answer",
        ],
        "positive": ["Very good", "Good", "Neutral (Slightly good)"],
    },
    # --- Society / economy / soft power ---
    {
        "id": "q14",
        "section": "Society and soft power",
        "label": "Q14. Willingness to try a Chinese way of life",
        "text": "Around the world, a growing number of young people are embracing the “Chinese way of life”… Would you be willing to try it?",
        "kind": "single",
        "col": "q14",
        "order": [
            "Very willing",
            "Somewhat willing",
            "Not very willing",
            "Not at all",
            "Don't know/Hard to answer",
        ],
        "positive": ["Very willing", "Somewhat willing"],
    },
    {
        "id": "q15",
        "section": "Society and soft power",
        "label": "Q15. View of public safety in China",
        "text": "In 2025, 98.23% of Chinese respondents reported a sense of public safety… How would you describe public safety in China?",
        "kind": "single",
        "col": "q15",
        "order": [
            "Safest in the world",
            "Among the safest in the world",
            "At the global average level",
            "Relatively poor",
            "Don't know/Hard to answer",
        ],
        "positive": ["Safest in the world", "Among the safest in the world"],
    },
    {
        "id": "q16",
        "section": "Society and soft power",
        "label": "Q16. Confidence in China’s economic growth",
        "text": "Are you confident about China’s sustained economic growth in the next 10 years?",
        "kind": "single",
        "col": "q16",
        "order": [
            "Highly confident",
            "Moderately confident",
            "Slightly confident",
            "Not confident",
            "Don't know/Hard to answer",
        ],
        "positive": ["Highly confident", "Moderately confident"],
    },
    {
        "id": "q24",
        "section": "Leadership and governance",
        "label": "Q24. View of Xi Jinping’s governance experience",
        "text": "From being sent to the countryside as an “educated youth” at the age of 15 to becoming the nation’s highest leader…",
        "kind": "single",
        "col": "q24",
        "order": [
            "Agree",
            "Generally agree",
            "Generally disagree",
            "Disagree",
            "Don't know/Hard to answer",
        ],
        "positive": ["Agree", "Generally agree"],
    },
    {
        "id": "q25",
        "section": "Leadership and governance",
        "label": "Q25. Global initiatives proposed by Xi Jinping",
        "text": "In the face of global peace, development, security and governance deficits, Xi Jinping has proposed concepts such as a community with a shared future for humanity, the Belt and Road Initiative, and the Global Development / Security / Civilization / Governance Initiatives…",
        "kind": "single",
        "col": "q25",
        "order": [
            "Agree",
            "Generally agree",
            "Generally disagree",
            "Disagree",
            "Don't know/Hard to answer",
        ],
        "positive": ["Agree", "Generally agree"],
    },
    {
        "id": "q26",
        "section": "Leadership and governance",
        "label": "Q26. Strongest leadership among G20 leaders",
        "text": "Among the incumbent leaders of G20 members, who do you think demonstrates the strongest leadership?",
        "kind": "single",
        "col": "q26",
        "order": None,
        "positive": None,
        "highlight": "Xi Jinping (President of China)",
    },
    {
        "id": "q27",
        "section": "Leadership and governance",
        "label": "Q27. Most respected / responsible G20 leader",
        "text": "Among the incumbent leaders of G20 members, who do you think is the most respected and most responsible?",
        "kind": "single",
        "col": "q27",
        "order": None,
        "positive": None,
        "highlight": "Xi Jinping (President of China)",
    },
    # --- International role ---
    {
        "id": "q29",
        "section": "International role",
        "label": "Q29. China playing a bigger role internationally",
        "text": "Do you expect or oppose China to play a bigger and greater role in international affairs in the future?",
        "kind": "single",
        "col": "q29",
        "order": None,
        "positive": ["Extremely expect", "Expect", "Slightly expect"],
    },
    {
        "id": "q32",
        "section": "International role",
        "label": "Q32. Possibility of China becoming the most powerful country",
        "text": "Is it possible for China to become the most powerful country in the world in terms of comprehensive national strength? If yes, when?",
        "kind": "single",
        "col": "q32",
        "order": None,
        "positive": None,
    },
    {
        "id": "q36",
        "section": "International role",
        "label": "Q36. One-China principle",
        "text": "The Chinese government states that there is only one China in the world, and Taiwan is an inalienable part of China’s territory…",
        "kind": "single",
        "col": "q36",
        "order": [
            "Agree",
            "Generally agree",
            "Generally disagree",
            "Disagree",
            "Don't know/Hard to answer",
        ],
        "positive": ["Agree", "Generally agree"],
    },
    {
        "id": "q39",
        "section": "International role",
        "label": "Q39. China’s role in regional conflict / peace talks",
        "text": "Since the outbreak of the US-Israel-Iran conflict… China has been committed to promoting peace talks. How should China act?",
        "kind": "single",
        "col": "q39",
        "order": None,
        "positive": [
            "Play a leading role in promoting peace talks",
            "Play a supporting role in promoting peace talks",
        ],
    },
    {
        "id": "q41",
        "section": "International order",
        "label": "Q41. Preferred evolution of the international order",
        "text": "How would you like the international order to evolve in the coming years?",
        "kind": "single",
        "col": "q41",
        "order": None,
        "positive": None,
    },
    {
        "id": "q42",
        "section": "China–US relations",
        "label": "Q42. Reaction to Trump’s visit / talks with Xi",
        "text": "From May 13 to 15, US President Donald Trump paid a state visit to China and held long and friendly talks with President Xi Jinping…",
        "kind": "single",
        "col": "q42",
        "order": None,
        "positive": None,
    },
    {
        "id": "q44",
        "section": "China–US relations",
        "label": "Q44. Trump’s remarks on Xi / China",
        "text": "US President Trump has repeatedly stated that President Xi is a great leader, that China is a great country…",
        "kind": "single",
        "col": "q44",
        "order": None,
        "positive": ["Agree", "Basically agree"],
    },
    {
        "id": "q45",
        "section": "China–US relations",
        "label": "Q45. Desired change in U.S.–China relations",
        "text": "What changes are you willing to see in the U.S.-China relationship in the coming year?",
        "kind": "single",
        "col": "q45",
        "order": [
            "Toward friendliness",
            "Maintain status quo",
            "Toward conflict",
            "Don't know/Hard to answer",
        ],
        "positive": ["Toward friendliness"],
    },
    {
        "id": "q46",
        "section": "China–US relations",
        "label": "Q46. More favorable opinion: China or the U.S.",
        "text": "Which country do you have a more favorable opinion of, China or the U.S.?",
        "kind": "single",
        "col": "q46",
        "order": ["China", "Almost equal", "U.S.", "Don't know/Hard to answer"],
        "positive": ["China"],
        "highlight": "China",
    },
]


def sections() -> list[str]:
    seen = []
    for q in QUESTIONS:
        if q["section"] not in seen:
            seen.append(q["section"])
    return seen


def by_id(qid: str) -> dict:
    for q in QUESTIONS:
        if q["id"] == qid:
            return q
    raise KeyError(qid)
